Repository Walkhub/Walkhub-AdminWeb, pull requests merged in 2022-03, with the labels that each got.

#104 🔀 :: (#102) su home
  src/components/home/SchoolFilter.tsx
  src/components/home/StudentFilter.tsx
  src/components/home/cards/SchoolCard.tsx
  src/components/home/index.tsx
  src/components/home/lists/ChallengeList.tsx
  src/components/home/lists/ClassList.tsx
  src/components/home/lists/SchoolList.tsx
  src/components/home/lists/StudentList.tsx
  src/hooks/useAuthCheck.tsx
  src/pages/index.tsx
Labels: chore, 기능 추가, 리팩토링

#105 🔀 :: (#103) su권한일때 header 수정
  src/components/common/header/index.tsx
Labels: chore

#106 🔀 :: (#101) school management
  src/components/schoolManagement/index.tsx
  src/pages/su/index.tsx
  src/utils/interfaces/school.ts
Labels: 기능 추가

#95 🔀 :: (#60) 공지사항 페이지 퍼블리싱 및 api 연결
  src/components/common/DeleteBtn.tsx
  src/components/common/defaultBtn/DefaultBtn.tsx
  src/components/notice/MakeNotice.tsx
  src/components/notice/NoticeForm.tsx
  src/components/notice/index.tsx
  src/pages/index.tsx
  src/pages/notice/index.tsx
  src/utils/interfaces/notice.ts
Labels: chore, 기능 추가

#110 🔀:: (#39) class
  src/components/class/.gitkeep
  src/components/class/seeClass/Class.tsx
  src/components/class/seeClass/ClassStudentList.tsx
  src/pages/class/[classid].tsx
  src/pages/index.tsx
  src/utils/interfaces/detailClass.ts
Labels: 기능 추가

#112 🔀 :: (#111) userDetail 자잘한 수정
  .yarn/cache/@emotion-styled-npm-11.6.0-497e1da808-612bbf114a.zip
  src/components/certification/index.tsx
  src/components/common/DefaultModal.tsx
  src/components/login/index.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/userdetail/measurement.tsx
  src/utils/axios/index.ts
Labels: chore, 기능 추가, 리팩토링
