Repository Walkhub/Walkhub-AdminWeb, pull requests merged in 2022-04, with the labels that each got.

#121 🔀 :: (#113) su make root
  src/components/class/seeClass/Class.tsx
  src/components/common/defaultBtn/DefaultBtn.tsx
  src/components/su/MakeRoot.tsx
  src/components/su/ModifyRoot.tsx
  src/components/su/Reissuance.tsx
  src/components/su/RootResult.tsx
  src/pages/404.tsx
  src/pages/class/[classid].tsx
  src/pages/class/[id].tsx
  src/pages/su/issuance/index.tsx
  src/pages/su/make/index.tsx
  src/pages/su/modify/index.tsx
  src/pages/su/result/index.tsx
  src/utils/apis/su/index.ts
  src/utils/apis/teachers/index.ts
  src/utils/axios/index.ts
  src/utils/interfaces/class.ts
  src/utils/interfaces/detailClass.ts
  src/utils/interfaces/su.ts
Labels: 기능 추가

#127 🔀 :: (#126) 달력 작동 안 하던것과 그 외 자잘한 수정
  src/components/challengeCreate/goal.tsx
  src/components/challengeCreate/index.tsx
  src/components/challengeDetail/challengeInfo.tsx
  src/components/common/search/options.tsx
  src/hooks/challenge/useCalendar.tsx
  src/hooks/challenge/useChallenge.tsx
  src/pages/challenge/modify/[id].tsx
  src/utils/apis/challenges/index.ts
Labels: chore, 버그

#128 🔀 :: (#123) 공지사항 점검
  src/components/notice/MakeNotice.tsx
  src/components/notice/NoticeForm.tsx
  src/components/notice/index.tsx
  src/pages/notice/index.tsx
  src/utils/interfaces/notice.ts
Labels: chore, 기능 추가, DOCS
