Repository Walkhub/Walkhub-AdminWeb, pull requests merged in 2022-05, with the labels that each got.

#135 🔀 :: (#122) class inspection
  src/components/class/makeclass/MakeClass.tsx
  src/components/class/seeClass/Class.tsx
  src/components/class/seeClass/ClassStudentList.tsx
  src/components/common/defaultBtn/DefaultBtn.tsx
  src/components/common/header/index.tsx
  src/components/home/lists/ClassList.tsx
  src/pages/class/[id].tsx
  src/utils/apis/teachers/index.ts
Labels: chore, 기능 추가

#137 🔀 :: (#136) Class getExcel 함수 인자 수정
  src/components/class/seeClass/ClassStudentList.tsx
Labels: chore, 리팩토링

#134 🔀 :: (#133) 링크 수정이랑 api url 수정
  src/components/challengeList/ChallengeCard.tsx
  src/components/challengeList/index.tsx
  src/components/home/SchoolFilter.tsx
  src/components/home/StudentFilter.tsx
  src/components/home/cards/ChallengeCard.tsx
  src/components/home/cards/ClassCard.tsx
  src/components/home/lists/ChallengeList.tsx
  src/components/home/lists/ClassList.tsx
  src/components/home/lists/SchoolList.tsx
  src/components/home/lists/StudentList.tsx
  src/components/schoolManagement/index.tsx
  src/pages/challenge/index.tsx
  src/pages/index.tsx
  src/pages/su/index.tsx
  src/utils/apis/school/index.ts
  src/utils/interfaces/challenge.ts
Labels: chore, 기능 추가

#139 🔀 :: (#130) su refactoring
  src/components/su/MakeRoot.tsx
  src/components/su/Reissuance.tsx
Labels: chore, 리팩토링

#140 🔀 :: (#138) 이것저것 수정
  src/components/challengeList/index.tsx
  src/components/home/SchoolInfo.tsx
  src/components/home/StudentFilter.tsx
  src/components/teacherManagement/MySchoolInfo.tsx
  src/components/teacherManagement/index.tsx
  src/pages/index.tsx
  src/pages/teacher-management/index.tsx
Labels: chore, 기능 추가

#142 🔀 :: (#141) class link
  src/components/challengeList/index.tsx
  src/components/home/lists/ClassList.tsx
Labels: chore, 버그

#145 🔀:: (#144) file 명 수정 및 폴더 명 수정
  src/components/su/CreateRoot.tsx
  src/pages/su/create/index.tsx
Labels: chore, 리팩토링
