Repository Walkhub/Walkhub-AdminWeb, pull requests merged in 2022-02, with the labels that each got.

#4 🔀 :: (#3) reviewer 자동화
  .github/CODEOWNERS
Labels: 프로젝트 설정

#7 🔀 :: (#6) context provider combine
  .gitignore
  src/contexts/.gitkeep
  src/contexts/index.tsx
  src/pages/_app.tsx
Labels: 기능 추가

#10 🔀 :: (#9) fixed context provider
  src/contexts/index.tsx
  src/pages/_app.tsx
Labels: 버그

#12 🔀 :: (#11) login context 추가
  src/contexts/LoginContext.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: 기능 추가

#16 🔀 :: (#15) root context 수정
  src/contexts/index.tsx
  src/pages/_app.tsx
  src/utils/function/RootProvider.tsx
Labels: chore

#19 🔀 :: (#18) chart
  .pnp.cjs
  .yarn/cache/@types-d3-color-npm-2.0.3-b3df41bc27-b4a963b15f.zip
  .yarn/cache/@types-d3-interpolate-npm-2.0.2-364e885e58-78c47193da.zip
  .yarn/cache/@types-d3-path-npm-1.0.9-76aa062ec1-acbf7376fd.zip
  .yarn/cache/@types-d3-path-npm-2.0.1-08e443f12a-2fe04503ec.zip
  .yarn/cache/@types-d3-scale-npm-3.3.2-7d60a8ce15-65dbf85f07.zip
  .yarn/cache/@types-d3-shape-npm-1.3.8-853cc04fad-a7f78a3f0b.zip
  .yarn/cache/@types-d3-shape-npm-2.1.3-a086344be9-d0855a1e2c.zip
  .yarn/cache/@types-d3-time-npm-2.1.1-e062b58f80-115048d0cd.zip
  .yarn/cache/@types-react-is-npm-17.0.3-1deb53884e-6abb7c47d5.zip
  .yarn/cache/@types-recharts-npm-1.8.23-b77b72eaef-0588f6245f.zip
  .yarn/cache/@types-resize-observer-browser-npm-0.1.7-9c439a421b-0377eaac8b.zip
  .yarn/cache/classnames-npm-2.3.1-f2ae0a8d3c-14db8889d5.zip
  .yarn/cache/css-unit-converter-npm-1.1.2-277ce2166c-0788803334.zip
  .yarn/cache/d3-array-npm-2.12.1-104e51ecda-97853b7b52.zip
  .yarn/cache/d3-color-npm-2.0.0-e7f04a5d87-b887354aa3.zip
  .yarn/cache/d3-format-npm-2.0.0-74628e435e-c4d3c8f994.zip
  .yarn/cache/d3-interpolate-npm-2.0.1-7e198300b3-4a2018ac34.zip
  .yarn/cache/d3-path-npm-2.0.0-6d1499464f-e39e91dfb9.zip
  .yarn/cache/d3-scale-npm-3.3.0-6a8f0391dc-f77e73f0fb.zip
  .yarn/cache/d3-shape-npm-2.1.0-9537c858fd-4a82a83fbb.zip
  .yarn/cache/d3-time-format-npm-3.0.0-0803464fb3-c20c1667db.zip
  .yarn/cache/d3-time-npm-2.1.1-73fdf673f7-d1c7b9658c.zip
  .yarn/cache/decimal.js-light-npm-2.5.1-2a858493a8-f5a2c7eac1.zip
  .yarn/cache/dom-helpers-npm-3.4.0-5d3cdecaac-58d9f1c4a9.zip
  .yarn/cache/eventemitter3-npm-4.0.7-7afcdd74ae-1875311c42.zip
  .yarn/cache/fast-equals-npm-2.0.4-4807826768-1aac8a2e16.zip
  .yarn/cache/internmap-npm-1.0.1-658c30de3f-9d00f8c0cf.zip
  .yarn/cache/lodash-npm-4.17.21-6382451519-eb835a2e51.zip
  .yarn/cache/performance-now-npm-2.1.0-45e3ce7e49-534e641aa8.zip
  .yarn/cache/postcss-value-parser-npm-3.3.1-24ecbb1b05-62cd26e1cd.zip
  .yarn/cache/prop-types-npm-15.8.1-17c71ee7ee-c056d3f1c0.zip
  .yarn/cache/raf-npm-3.4.1-c25d48d76e-50ba284e48.zip
  .yarn/cache/react-lifecycles-compat-npm-3.0.4-d5e285a39e-a904b0fc0a.zip
  .yarn/cache/react-resize-detector-npm-6.7.8-5552cc4a85-dc8acbe216.zip
  .yarn/cache/react-smooth-npm-2.0.0-a0a105f065-4eff3fb930.zip
  .yarn/cache/react-transition-group-npm-2.9.0-fe7767fa8d-d8c9e50aab.zip
  .yarn/cache/recharts-npm-2.1.9-632743dbb5-5751ba78b0.zip
  .yarn/cache/recharts-scale-npm-0.4.5-30646fd0f5-e970377190.zip
  .yarn/cache/reduce-css-calc-npm-2.1.8-e2acd211e5-8fd27c06c4.zip
  .yarn/cache/resize-observer-polyfill-npm-1.5.1-603120e8a0-57e7f79489.zip
  package.json
  src/components/Chart/index.tsx
  src/hooks/useChartData.ts
  yarn.lock
Labels: 기능 추가

#23 🔀 :: (#22) absolute path 설정
  src/pages/_app.tsx
  src/pages/index.tsx
  tsconfig.json
Labels: 프로젝트 설정

#20 🔀 :: (#13) notice context
  src/contexts/NoticeContext.tsx
  src/contexts/index.tsx
  src/pages/_app.tsx
Labels: 기능 추가

#28 🔀 :: (#25) prettier setting
  .prettierrc
  .vscode/settings.json
  src/components/Chart/index.tsx
  src/hooks/useChartData.ts
  src/pages/api/hello.ts
  src/pages/login/index.tsx
Labels: 프로젝트 설정

#30 🔀 :: (#27) school class context
  src/contexts/ClassPostContext.tsx
  src/contexts/NoticeContext.tsx
  src/contexts/index.tsx
  src/pages/_app.tsx
Labels: chore, 기능 추가

#34 🔀 :: (#32) context 제거
  src/contexts/ClassPostContext.tsx
  src/contexts/NoticeContext.tsx
  src/contexts/index.tsx
  src/pages/_app.tsx
Labels: 리팩토링

#38 🔀 :: (#37) 기본 스타일 수정
  src/styles/emotion.d.ts
  src/styles/global.ts
  src/styles/theme.ts
Labels: chore

#43 🔀 :: (#42) bright gray 추가
  src/styles/emotion.d.ts
  src/styles/theme.ts
Labels: chore

#45 🔀 :: (#44) login page 퍼블리싱
  src/components/login/index.tsx
  src/pages/login/index.tsx
Labels: 기능 추가

#49 🔀 :: (#48) cookie typing error
  src/utils/axios/index.ts
  src/utils/function/tokenManager.ts
Labels: chore

#41 🔀 :: (#40) Default Button
  src/components/common/defaultBtn/DefaultBtn.tsx
Labels: 기능 추가

#33 🔀 :: (#31) 그래프 일주일 마다 색깔 추가
  src/components/Chart/index.tsx
  src/components/chart/index.tsx
  src/hooks/useChartData.ts
  src/utils/function/getChartData.ts
Labels: chore

#58 🔀 :: (#57) header ui
  src/components/common/header/index.tsx
Labels: 기능 추가

#67 🔀 :: (#24) code certification publishing
  src/components/certification/CodeInputBox.tsx
  src/components/certification/index.tsx
  src/pages/login/certification.tsx
Labels: 기능 추가

#71 🔀 :: (#70) useAuthrity 생성
  src/hooks/useAuthrity.ts
Labels: 기능 추가

#73 🔀 :: (#72) 로그인 기능 추가
  src/components/login/index.tsx
  src/hooks/useAuthrity.ts
  src/utils/apis/auth/index.ts
  src/utils/axios/index.ts
  src/utils/interfaces/auth.ts
Labels: 기능 추가

#77 🔀 :: (#74) 선생님 인증코드 확인 기능 추가
  src/components/certification/CodeInputBox.tsx
  src/components/certification/index.tsx
  src/components/login/index.tsx
  src/hooks/useAuthority.ts
  src/hooks/useAuthrity.ts
  src/utils/apis/teachers/index.ts
  src/utils/interfaces/auth.ts
Labels: 기능 추가

#76 🔀 :: (#75) hoc 추가
  src/hocs/withAuth.tsx
  src/hooks/useAuthority.ts
  src/utils/function/fetcher.ts
Labels: chore, 기능 추가

#80 🔀 :: (#79) home page
  src/components/common/dropdown/index.tsx
  src/components/home/ChallengeList.tsx
  src/components/home/ClassList.tsx
  src/components/home/StudentFilter.tsx
  src/components/home/StudentList.tsx
  src/components/home/cards/ChallengeCard.tsx
  src/components/home/cards/ClassCard.tsx
  src/components/home/cards/StudentCard.tsx
  src/components/home/cards/studentCard/StudentCard.tsx
  src/components/home/index.tsx
  src/pages/index.tsx
  src/utils/interfaces/challenge.ts
  src/utils/interfaces/class.ts
  src/utils/interfaces/student.ts
Labels: chore, 기능 추가

#83 🔀 :: (#81) 404 page not found 퍼블리싱
  src/pages/404.tsx
Labels: 기능 추가

#87 🔀 :: (#84) 헤더 text 가운데 정렬
  src/components/common/header/index.tsx
Labels: chore

#88 🔀 :: (#85) teacher managements page
  src/components/common/defaultBtn/DefaultBtn.tsx
  src/components/teacherManagement/TeacherCard.tsx
  src/components/teacherManagement/index.tsx
  src/pages/teacher-management/index.tsx
Labels: 기능 추가

#89 🔀 :: (#86) challenge list ui
  src/components/challengeList/ChallengeCard.tsx
  src/components/challengeList/index.tsx
  src/pages/challenge/index.tsx
Labels: 기능 추가

#94 🔀 :: (#68) user detail publishing
  .pnp.cjs
  .yarn/cache/@babel-runtime-npm-7.16.5-324a158d8a-b96e67280e.zip
  src/components/chart/index.tsx
  src/components/common/DefaultModal.tsx
  src/components/common/ProfileBox.tsx
  src/components/login/index.tsx
  src/components/userDetail/index.tsx
  src/components/userDetail/measurement/Map.tsx
  src/components/userDetail/measurement/MeasurementCard.tsx
  src/components/userDetail/measurement/index.tsx
  src/hooks/useAuthority.ts
  src/pages/userdetail/index.tsx
  src/pages/userdetail/measurement.tsx
  src/utils/function/localstorgeAuthority.ts
Labels: 기능 추가

#98 🔀 :: (#97) 선생님 관리 페이지
  src/components/teacherManagement/TeacherCard.tsx
  src/components/teacherManagement/index.tsx
  src/pages/teacher-management/index.tsx
  src/utils/axios/index.ts
  src/utils/interfaces/teacher.ts
Labels: chore, 기능 추가

#100 🔀 :: (#99) home page 수정
  src/components/home/ClassList.tsx
  src/components/home/StudentFilter.tsx
Labels: chore, 기능 추가
